services:
  mongodb:
    image: mongo:latest
    container_name: agendador-tarefas
    restart: no
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongodb-server
    volumes:
      - ./mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: 512M
volumes:
  mongo_data:
