spring.application.name=agendador-tarefas

usuario.url=localhost:8080

spring.mongodb.uri=mongodb://admin:mongodb-server@localhost:27017/db_agendador?authSource=admin

logging.level.org.springframework.security=TRACE

server.port=8081